apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Configuration and service definition
- flink-configuration-configmap.yaml
- jobmanager-service.yaml
# Create the deployments for the cluster
- jobmanager-session-deployment-non-ha.yaml
- taskmanager-session-deployment.yaml
